from __future__ import annotations


def build_debugger_css() -> str:
    return r'''
.cui-debugger-trigger-wrap{position:relative;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto;margin-left:8px}
.cui-debugger-trigger{color:var(--cui-text-secondary)!important}
.cui-debugger-trigger:hover{color:var(--cui-text-primary)!important;background:var(--cui-surface-hover)!important}
.cui-debugger-trigger-badge{position:absolute;right:-3px;top:-2px;min-width:16px;height:16px;padding:0 4px;border-radius:999px;display:flex;align-items:center;justify-content:center;background:var(--cui-danger);color:white;font-size:9px;font-weight:700;line-height:1;box-shadow:0 0 0 2px var(--cui-surface)}
.cui-debugger-shell{position:fixed;inset:12px;display:flex;flex-direction:column;min-width:0;min-height:0;background:var(--cui-surface-elevated);border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-overlay);box-shadow:0 26px 90px rgba(0,0,0,.28);overflow:hidden;color:var(--cui-text-primary)}
.cui-debugger-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 14px;border-bottom:1px solid var(--cui-border-subtle);background:var(--cui-surface)}
.cui-debugger-header__title{display:flex;align-items:center;gap:10px;min-width:0}.cui-debugger-title{font-size:16px;font-weight:720;line-height:20px}.cui-debugger-subtitle{font-size:11px;color:var(--cui-text-tertiary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cui-debugger-header__actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}
.cui-debugger-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;padding:10px 14px;background:var(--cui-surface-secondary);border-bottom:1px solid var(--cui-border-subtle)}
.cui-debugger-kpi{display:flex;align-items:baseline;gap:8px;min-width:0;padding:8px 10px;background:var(--cui-surface);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-surface)}.cui-debugger-kpi__value{font-variant-numeric:tabular-nums;font-weight:750;font-size:17px}.cui-debugger-kpi__label{font-size:10.5px;color:var(--cui-text-tertiary)}
.cui-debugger-tabs{padding:0 10px;border-bottom:1px solid var(--cui-border-subtle);background:var(--cui-surface)}.cui-debugger-panels{flex:1 1 auto;min-height:0;width:100%;background:var(--cui-page)!important}.cui-debugger-panels>.q-panel{min-height:0}.cui-debugger-panels .q-tab-panel{height:100%;overflow:auto;padding:12px 14px}
.cui-debugger-stream{display:flex;flex-direction:column;gap:6px;min-width:0}.cui-debugger-row,.cui-debugger-request-row{display:grid;align-items:start;gap:8px;padding:8px 10px;background:var(--cui-surface);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-control)}.cui-debugger-row{grid-template-columns:72px minmax(0,1fr)}.cui-debugger-row__level{font-size:10px;font-weight:750;color:var(--cui-text-tertiary)}.cui-debugger-row.is-warning .cui-debugger-row__level{color:var(--cui-warning)}.cui-debugger-row.is-error .cui-debugger-row__level,.cui-debugger-row.is-critical .cui-debugger-row__level{color:var(--cui-danger)}.cui-debugger-row__body{display:flex;flex-direction:column;gap:3px;min-width:0}.cui-debugger-row__message{font-size:12px;line-height:17px;font-weight:620;white-space:pre-wrap;overflow-wrap:anywhere}.cui-debugger-row__meta{font-size:10px;color:var(--cui-text-tertiary);font-variant-numeric:tabular-nums}.cui-debugger-row__context,.cui-debugger-stack,.cui-debugger-event-row,.cui-debugger-pre{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;font-size:10.5px;line-height:15px;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--cui-text-secondary)}
.cui-debugger-error-card{display:flex;flex-direction:column;gap:5px;padding:10px 12px;background:var(--cui-danger-soft);border:1px solid color-mix(in srgb,var(--cui-danger) 30%,var(--cui-border-subtle));border-radius:var(--cui-radius-surface)}
.cui-debugger-request-row{grid-template-columns:54px 52px minmax(0,1fr) 86px}.cui-debugger-request-row__method,.cui-debugger-request-row__status,.cui-debugger-request-row__time{font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums}.cui-debugger-request-row__path{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cui-debugger-request-row__time{text-align:right;color:var(--cui-text-tertiary)}
.cui-debugger-event-row,.cui-debugger-pre{display:block;padding:10px 12px;background:var(--cui-surface);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-control)}.cui-debugger-empty{padding:18px;color:var(--cui-text-tertiary);font-size:12px}
.cui-sidebar-version{display:flex;flex-direction:column;gap:2px;padding:7px 8px 3px;border-top:1px solid var(--cui-border-subtle);margin-top:2px}.cui-sidebar-version__label{font-size:9px;line-height:12px;letter-spacing:.06em;text-transform:uppercase;color:var(--cui-text-tertiary)}.cui-sidebar-version__value{font-size:10px;line-height:14px;color:var(--cui-text-secondary);font-variant-numeric:tabular-nums}.cui-sidebar-version__runtime{font-size:9.5px;line-height:13px;color:var(--cui-text-tertiary)}
html[data-sidebar='compact'] .cui-sidebar-version{align-items:center;padding-inline:0}.cui-sidebar-version__compact{display:none}html[data-sidebar='compact'] .cui-sidebar-version__full{display:none}html[data-sidebar='compact'] .cui-sidebar-version__compact{display:block;font-size:9px;font-weight:700;color:var(--cui-text-tertiary)}
@media(max-width:760px){.cui-debugger-shell{inset:0;border:0;border-radius:0}.cui-debugger-header{align-items:flex-start}.cui-debugger-header__actions .cui-button{display:none!important}.cui-debugger-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-debugger-request-row{grid-template-columns:50px 46px minmax(0,1fr)}.cui-debugger-request-row__time{grid-column:3;text-align:left}.cui-debugger-subtitle{display:none}}
'''.strip() + '\n'


__all__ = ['build_debugger_css']
