from __future__ import annotations

WORKBENCH_CSS = r'''
.cui-workbench-page{max-width:1600px;margin:0 auto;padding:28px 30px 56px;width:100%;}
.cui-workbench-hero{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,.7fr);gap:24px;padding:28px;border:1px solid var(--cui-border,#d9dee7);border-radius:18px;background:var(--cui-surface,#fff);}
.cui-workbench-eyebrow{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;opacity:.68;}
.cui-workbench-title{font-size:34px;font-weight:750;line-height:1.12;letter-spacing:-.025em;margin-top:6px;}
.cui-workbench-subtitle{font-size:15px;line-height:1.6;max-width:780px;opacity:.76;margin-top:8px;}
.cui-workbench-search{margin-top:20px;max-width:760px;width:100%;}
.cui-workbench-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;align-content:start;}
.cui-workbench-kpi{padding:14px 16px;border-radius:12px;border:1px solid var(--cui-border,#d9dee7);background:var(--cui-surface-subtle,#f7f8fa);}
.cui-workbench-kpi strong{display:block;font-size:24px;line-height:1.1}.cui-workbench-kpi span{font-size:12px;opacity:.68}
.cui-workbench-section{margin-top:30px}.cui-workbench-section-head{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:12px}
.cui-workbench-section-title{font-size:20px;font-weight:720}.cui-workbench-section-copy{font-size:13px;opacity:.68;max-width:760px}
.cui-workbench-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.cui-workbench-grid--3{grid-template-columns:repeat(3,minmax(0,1fr))}
.cui-workbench-card{display:flex;flex-direction:column;gap:8px;min-height:150px;padding:16px;border:1px solid var(--cui-border,#d9dee7);border-radius:14px;background:var(--cui-surface,#fff);transition:border-color .12s ease,transform .12s ease;cursor:pointer}
.cui-workbench-card:hover{transform:translateY(-1px);border-color:var(--cui-primary,#356df3)}
.cui-workbench-card:focus-visible{outline:2px solid var(--cui-primary,#356df3);outline-offset:2px;border-color:var(--cui-primary,#356df3)}
.cui-workbench-card__meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap;font-size:11px;font-weight:650;text-transform:uppercase;letter-spacing:.04em;opacity:.64}
.cui-workbench-card__title{font-size:15px;font-weight:700;line-height:1.3}.cui-workbench-card__body{font-size:13px;line-height:1.5;opacity:.75}
.cui-workbench-chiprow{display:flex;gap:6px;flex-wrap:wrap;margin-top:auto}.cui-workbench-chip{font-size:11px;padding:3px 7px;border-radius:999px;background:var(--cui-surface-subtle,#f1f3f6);}
.cui-workbench-catalog-results{display:flex;flex-direction:column;gap:4px}.cui-workbench-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:14px}.cui-workbench-toolbar .q-field{min-width:240px}
.cui-workbench-command-trigger{align-self:flex-start;margin:4px 0 8px}.cui-workbench-command-shortcut{font-size:10px;opacity:.62;margin-left:6px}
.cui-workbench-display-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:4px 0 10px;padding:8px 10px;border:1px solid var(--cui-border,#d9dee7);border-radius:12px;background:var(--cui-surface-subtle,#f7f8fa)}.cui-workbench-display-controls__label{font-size:11px;font-weight:700;letter-spacing:.03em;opacity:.68}.cui-workbench-display-controls__label:not(:first-child){margin-left:4px}
.cui-workbench-preview{padding:18px;border:1px solid var(--cui-border,#d9dee7);border-radius:14px;background:var(--cui-surface,#fff);min-height:300px}
.cui-workbench-two{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.7fr);gap:18px}
.cui-workbench-list{display:flex;flex-direction:column;gap:12px}.cui-workbench-search-group{display:flex;flex-direction:column;gap:8px}.cui-workbench-search-group__title{font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.06em;opacity:.62}.cui-workbench-note{font-size:12px;line-height:1.5;opacity:.7}
.cui-workbench-preview-title{font-size:14px;font-weight:700;margin-bottom:8px}.cui-workbench-preview-caption{font-size:11px;line-height:1.45;opacity:.65;margin-top:10px}.cui-workbench-preview-empty{display:flex;align-items:center;justify-content:center;min-height:110px;border:1px dashed var(--cui-border,#d9dee7);border-radius:10px;font-size:12px;opacity:.62}.cui-workbench-mini-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.cui-workbench-mini-grid--strip{grid-template-columns:repeat(5,minmax(110px,1fr));overflow-x:auto}.cui-workbench-mini-panel{min-width:0;overflow:hidden}.cui-workbench-flow{display:flex;align-items:stretch;gap:8px;overflow-x:auto;padding:8px 2px}.cui-workbench-flow__node{min-width:128px;flex:1;padding:12px;border:1px solid var(--cui-border,#d9dee7);border-radius:10px;background:var(--cui-surface-subtle,#f7f8fa)}.cui-workbench-flow__title{font-size:13px;font-weight:700}.cui-workbench-flow__arrow{display:flex;align-items:center;font-size:20px;opacity:.5}.cui-workbench-tree{display:flex;flex-direction:column;gap:10px}.cui-workbench-tree__root{align-self:flex-start;padding:8px 12px;border-radius:9px;background:var(--cui-surface-subtle,#f1f3f6);font-size:13px;font-weight:700}.cui-workbench-tree__branches{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.cui-workbench-tree__branch{padding:10px;border-left:2px solid var(--cui-border,#d9dee7);background:var(--cui-surface-subtle,#f7f8fa);border-radius:0 9px 9px 0}.cui-workbench-tree__branch-title{font-size:12px;font-weight:700;margin-bottom:5px}.cui-workbench-tree__leaf{font-size:11px;line-height:1.45;opacity:.72}.cui-workbench-recipe-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:12px}.cui-workbench-recipe-panel{display:flex;flex-direction:column;gap:8px;min-width:0;padding:14px;border:1px solid var(--cui-border,#d9dee7);border-radius:12px;background:var(--cui-surface,#fff)}.cui-workbench-panel-preview{min-height:128px;min-width:0;overflow:hidden}.cui-workbench-panel-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:auto}.cui-workbench-records{display:flex;flex-direction:column;border:1px solid var(--cui-border,#d9dee7);border-radius:9px;overflow:hidden}.cui-workbench-records__row{display:grid;grid-template-columns:.8fr .6fr 1.4fr .7fr .7fr;gap:6px;padding:7px 9px;border-top:1px solid var(--cui-border,#d9dee7);font-size:10px}.cui-workbench-records__row:first-child{border-top:0}.cui-workbench-records__head{font-weight:700;background:var(--cui-surface-subtle,#f7f8fa)}.cui-workbench-property-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cui-workbench-property-grid__item{padding:10px;border:1px solid var(--cui-border,#d9dee7);border-radius:9px;background:var(--cui-surface-subtle,#f7f8fa)}
.cui-workbench-not-found{display:flex;flex-direction:column;align-items:flex-start;gap:12px;min-height:180px}.cui-workbench-quality-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.cui-workbench-quality-card{padding:16px;border:1px solid var(--cui-border,#d9dee7);border-radius:12px;background:var(--cui-surface,#fff)}.cui-workbench-quality-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:9px}

.cui-studio-header{display:flex;flex-direction:column;gap:8px;padding:18px;margin-bottom:14px;border:1px solid var(--cui-border,#d9dee7);border-radius:14px;background:var(--cui-surface,#fff)}
.cui-studio-preview-frame{width:100%;margin:12px auto;padding:14px;border:1px solid var(--cui-border,#d9dee7);border-radius:12px;background:var(--cui-surface,#fff);transition:max-width .15s ease}
.cui-studio-preview-controls{align-items:flex-end}.cui-studio-iframe{display:block;width:100%;height:560px;border:1px solid var(--cui-border,#d9dee7);border-radius:10px;background:var(--cui-surface,#fff)}
.cui-studio-event-log{margin-top:12px;padding:9px 11px;border:1px solid var(--cui-border,#d9dee7);border-radius:10px;background:var(--cui-surface-subtle,#f7f8fa)}.cui-studio-event-log summary{cursor:pointer;font-weight:700}.cui-studio-event-log__events{display:flex;flex-direction:column;gap:3px;padding-top:8px}
.cui-data-dock-content{display:flex;flex-direction:column;gap:12px;margin-top:12px}.cui-data-dock-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.cui-data-dock-issues{display:flex;flex-direction:column;gap:4px;padding:10px;border-left:3px solid var(--cui-warning,#d18b00);background:var(--cui-surface-subtle,#f7f8fa)}
.cui-data-dock-column{display:grid;grid-template-columns:minmax(150px,.7fr) minmax(0,1.8fr);gap:8px 14px;padding:12px;border:1px solid var(--cui-border,#d9dee7);border-radius:10px}.cui-data-dock-column__controls{grid-column:1/-1;display:grid;grid-template-columns:1.4fr 1fr 1fr auto;gap:8px;align-items:end}
.cui-recipe-mapping{display:flex;flex-direction:column;gap:10px}.cui-recipe-mapping__row{display:grid;grid-template-columns:minmax(150px,.7fr) minmax(0,1.2fr) minmax(220px,1fr);gap:8px 14px;align-items:end;padding:10px;border-bottom:1px solid var(--cui-border,#d9dee7)}.cui-recipe-panel-status{padding:10px 12px;border:1px solid var(--cui-border,#d9dee7);border-radius:10px}.cui-recipe-panel-status.is-unavailable,.cui-workbench-recipe-panel.is-unavailable{opacity:.58;background:var(--cui-surface-subtle,#f7f8fa)}
.cui-builder{display:flex;flex-direction:column;gap:16px}.cui-builder>.cui-segmented-control{align-self:flex-start}.cui-builder .cui-workbench-card{min-height:auto;cursor:default}.cui-workbench-disabled-state{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:14px;border:1px dashed var(--cui-border,#d9dee7);border-radius:10px}
@media(max-width:1100px){.cui-workbench-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-workbench-grid--3{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-workbench-hero,.cui-workbench-two{grid-template-columns:1fr}.cui-workbench-not-found{display:flex;flex-direction:column;align-items:flex-start;gap:12px;min-height:180px}.cui-workbench-quality-grid{grid-template-columns:1fr}.cui-workbench-mini-grid{grid-template-columns:1fr}.cui-workbench-tree__branches{grid-template-columns:1fr}}
@media(max-width:820px){.cui-data-dock-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-data-dock-column,.cui-recipe-mapping__row{grid-template-columns:1fr}.cui-data-dock-column__controls{grid-template-columns:1fr 1fr}.cui-studio-iframe{height:460px}}
@media(max-width:680px){.cui-workbench-display-controls{align-items:flex-start}.cui-workbench-page{padding:18px 14px 40px}.cui-workbench-grid,.cui-workbench-grid--3,.cui-workbench-recipe-grid{grid-template-columns:1fr}.cui-workbench-title{font-size:28px}.cui-workbench-records__row{grid-template-columns:1fr 1fr}.cui-workbench-flow{flex-direction:column}.cui-workbench-flow__arrow{transform:rotate(90deg);align-self:center}}
'''


def install_workbench_css() -> None:
    from nicegui import ui
    ui.add_css(WORKBENCH_CSS, shared=True)
