from __future__ import annotations
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, Mapping

from nicegui_base.analysis import AnalysisContext, AnalyticalPanelController, Selection, SelectionBus, SelectionKind, SelectionMutationMode

@dataclass(frozen=True,slots=True)
class SemiconductorSurfaceDefinition:
    key:str; category:str; purpose:str; use_when:tuple[str,...]; avoid_when:tuple[str,...]=(); linked_hover:bool=False; spatial:bool=False
    def __post_init__(self):
        defaults={
            'spc':'when chart assumptions, subgroup structure, or baseline definition do not match the data',
            'capability':'when specification limits, measurement-system quality, or population definition are unknown',
            'wafer':'when coordinates are unavailable or spatial sampling is too sparse for the intended inference',
            'fdc':'when sensor semantics, recipe-step alignment, or event timing are unavailable',
            'rca':'as proof of causality without corroborating engineering evidence',
            'yield':'when numerator/denominator or bin definitions are inconsistent across populations',
            'reliability':'when failure/censoring semantics or exposure time are unknown',
            'doe':'for observational data that were not generated by a valid designed experiment',
        }
        default=defaults.get(self.category)
        if default and default not in self.avoid_when: object.__setattr__(self,'avoid_when',tuple(self.avoid_when)+(default,))

_ITEMS=(
('spc_i_mr','spc','Individuals and moving-range control chart',('continuous measurements without rational subgroups',)),
('spc_xbar_r','spc','Xbar-R subgroup control chart',('small equal-size rational subgroups',)),('spc_xbar_s','spc','Xbar-S subgroup control chart',('equal-size subgroup variability matters',)),
('spc_p','spc','Proportion nonconforming control chart',('binary defect proportion with varying samples',)),('spc_np','spc','Count nonconforming control chart',('binary defect counts with constant sample size',)),
('spc_c','spc','Defect count control chart',('Poisson defect counts with constant opportunity',)),('spc_u','spc','Defects-per-unit control chart',('Poisson defects with varying opportunity',)),
('spc_ewma','spc','EWMA drift-sensitive control chart',('small sustained process shifts',)),('spc_cusum','spc','CUSUM change-detection chart',('small persistent mean shifts',)),
('capability_histogram','capability','Capability distribution with spec limits',('Cp/Cpk/Pp/Ppk and distribution shape',)),('qq_probability','capability','Normal probability/QQ diagnostic',('capability normality assumption review',)),('ecdf','capability','Empirical cumulative distribution',('distribution comparison without binning',)),('box_distribution','capability','Box distribution comparison',('compact affected/control distribution summaries',)),('violin_distribution','capability','Violin distribution comparison',('shape plus spread comparison',)),('ridge_distribution','capability','Ridge distribution comparison',('many tool/chamber distributions',)),
('wafer_continuous','wafer','Continuous wafer map',('continuous spatial metrology or process response',),(),True,True),('wafer_categorical','wafer','Categorical/bin wafer map',('yield bins or categorical spatial state',),(),True,True),('wafer_defect','wafer','Defect wafer map',('inspection defects and defect classes',),(),True,True),('wafer_delta','wafer','Affected minus control wafer delta map',('spatial process change localization',),(),True,True),('wafer_comparison','wafer','Side-by-side wafer comparison',('affected/control wafer signature comparison',),(),True,True),('lot_wafer_strip','wafer','Lot wafer strip',('lot-level wafer-to-wafer spatial variation',),(),True,True),('wafer_small_multiples','wafer','Synchronized wafer small multiples',('many wafers on one scale',),(),True,True),('wafer_contour','wafer','Contour/surface wafer map',('smooth spatial field interpretation',),('sparse categorical data',),True,True),('wafer_radial','wafer','Radial profile',('center-edge signatures',),(),True,True),('wafer_center_edge','wafer','Center-edge decomposition',('quantify center versus edge shift',),(),True,True),('wafer_ring','wafer','Ring analysis',('concentric process signatures',),(),True,True),('wafer_sector','wafer','Sector analysis',('azimuthal spatial signatures',),(),True,True),('wafer_defect_clusters','wafer','Defect-cluster overlays',('identify spatially clustered inspection defects',),(),True,True),
('fdc_recipe_step_trace','fdc','Recipe-step-aligned trace',('compare traces with step semantics',),(),True),('fdc_golden_envelope','fdc','Golden trace envelope',('compare trace deviation against baseline population',),(),True),('fdc_multi_sensor','fdc','Multi-sensor trace panel',('correlated equipment sensor behavior',),(),True),('fdc_tool_chamber_compare','fdc','Tool/chamber comparison',('matching and PM-effect comparisons',),(),True),('fdc_chamber_fingerprint','fdc','Chamber fingerprint',('multivariate chamber matching',)),('fdc_sensor_fingerprint','fdc','Sensor fingerprint',('sensor signature comparison',)),('fdc_alarm_overlay','fdc','Alarm overlay',('align alarms with trace excursions',),(),True),('fdc_equipment_event_overlay','fdc','Equipment event overlay',('align PM/recipe/equipment events with traces',),(),True),('fdc_pca_scores','fdc','PCA scores',('multivariate operating-state separation',)),('fdc_pca_loadings','fdc','PCA loadings',('variables driving multivariate separation',)),('fdc_hotelling_t2','fdc','Hotelling T²',('multivariate score-space anomaly magnitude',)),('fdc_spe_q','fdc','SPE/Q statistic',('PCA residual anomaly magnitude',)),
('rca_affected_control','rca','Affected/control population comparison',('quantify excursion shift without causal overclaim',)),('rca_commonality_ranking','rca','Commonality ranking',('rank shared factors across affected versus control',)),('rca_enrichment','rca','Enrichment analysis',('factor exposure over-representation',)),('rca_commonality_matrix','rca','Commonality matrix',('scan factor/value enrichment',)),('rca_contribution_waterfall','rca','Contribution waterfall',('show ranked contribution accumulation',)),('rca_correlation_matrix','rca','Correlation matrix',('numeric relationship screening',),('causal conclusions',)),('rca_evidence_matrix','rca','Evidence matrix',('hypothesis evidence/contradiction review',)),('rca_genealogy_graph','rca','Genealogy/process graph',('lot/wafer/tool/recipe route genealogy',)),('rca_cause_tree','rca','Cause tree',('structured causal candidates',)),('rca_fault_tree','rca','Fault tree',('logical failure decomposition',)),('rca_sankey','rca','Sankey/process flow',('population flow through route/tool/process paths',)),
('yield_pareto','yield','Yield loss Pareto',('rank yield-loss contributors',)),('bin_pareto','yield','Bin Pareto',('rank failing bins',)),('yield_waterfall','yield','Yield waterfall/decomposition',('explain yield delta composition',)),('weibull_reliability','reliability','Weibull reliability analysis',('time-to-failure reliability data',)),('doe_main_effects','doe','DOE main effects',('screen factor effects',)),('doe_interactions','doe','DOE interaction plot',('factor interaction assessment',)),('doe_response_surface','doe','DOE response surface',('quadratic two-factor response optimization',)),
)
SEMICONDUCTOR_SURFACE_REGISTRY:Mapping[str,SemiconductorSurfaceDefinition]=MappingProxyType({r[0]:SemiconductorSurfaceDefinition(*r) for r in _ITEMS})

def get_semiconductor_surface(key:str)->SemiconductorSurfaceDefinition:
    try:return SEMICONDUCTOR_SURFACE_REGISTRY[key]
    except KeyError as exc:raise KeyError(f'Unknown semiconductor analytical surface: {key}') from exc

class SemiconductorAnalyticalSurface:
    """Framework-neutral shared lifecycle/selection contract for semiconductor analytics."""
    def __init__(self,key:str,context:AnalysisContext,selections:SelectionBus, *, controller:AnalyticalPanelController|None=None)->None:
        self.definition=get_semiconductor_surface(key);self.context=context;self.selections=selections;self.controller=controller or AnalyticalPanelController();self._closed=False
    @property
    def key(self):return self.definition.key
    def loading(self,message:str|None=None):return self.controller.loading(message)
    def ready(self,message:str|None=None):return self.controller.ready(message)
    def empty(self,message:str|None='No data'):return self.controller.empty(message)
    def partial(self,reason:str,message:str|None=None):return self.controller.partial(reason,message)
    def stale(self,reason:str,message:str|None=None):return self.controller.stale(reason,message)
    def error(self,error:BaseException|str):return self.controller.error(error)
    def select(self,kind:SelectionKind,selection_id:str,values:Mapping[str,Any], *, mode:SelectionMutationMode=SelectionMutationMode.REPLACE,source:str|None=None):
        return self.selections.apply(Selection(kind,selection_id,values,source=source or self.key),mode=mode,source=source or self.key)
    def close(self):self._closed=True

__all__=['SEMICONDUCTOR_SURFACE_REGISTRY','SemiconductorAnalyticalSurface','SemiconductorSurfaceDefinition','get_semiconductor_surface']
